CREATE TABLE usertest(
    USER_ID varchar(32) NOT NULL PRIMARY KEY,
    PASSWORD varchar(128) NOT NULL
);
CREATE TABLE user(
    USER_ID varchar(32) NOT NULL PRIMARY KEY,
    PASSWORD varchar(128) NOT NULL
);