version: '3.3'

services:
  mariadb:
    image: mariadb
    restart: always
    secrets:
      - db_root_password
      - db_dba_password
    volumes:
      - BackendDb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      
      MYSQL_DATABASE: bankttsDB
      MYSQL_USER: banktts
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_dba_password
    ports:
      - '9001:9000'
secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_dba_password:
    file: ./secrets/db_password.txt
volumes: 
  BackendDb: